package com.api.v1.constants;

public class ResponseMessage {
    public static final String FIND_CHATTING_ROOM = "채팅방 정보조회 성공";
    public static final String PROTECTED_DEAL = "안전거래 생성 완료";
    public static final String FIND_PROTECTED_DEAL = "안전거래 조회 성공";
    public static final String FIND_MY_PROTECTED_DEAL = "내 안전거래 조회 성공";
    public static final String ACCEPT_DEAL = "안전 거래 요청 수락 성공";
    public static final String COMPLETE_DEAL = "안전 거래 완료";
    public static final String CANCEL_BEFORE_WITHDRAW_DEAL = "입금전, 안전거래 취소";
    public static final String CANCEL_AFTER_WITHDRAW_DEAL = "입금후, 거래 취소";
    public static final String VERIFICATION_CODE_SENT_SUCCESS = "이메일로 인증 번호 전송 성공";
    public static final String EMAIL_VERIFICATION_SUCCESS = "이메일 인증 성공";
    public static final String SIGN_UP_SUCCESS = "회원가입 성공";
    public static final String MY_PROFILE_RETRIEVE = "내 프로필 조회 성공";
    public static final String MY_ACCOUNT_REGISTER = "내 계좌 정보 등록 성공";
    public static final String MY_ACCOUNT_FIND = "내 계좌 정보 조회 성공";
    public static final String MY_ACCOUNT_UPDATE = "계좌 정보 수정 성공";
    public static final String MY_ACCOUNT_EXIST = "계좌 존재 여부 조회 성공";
    public static final String MY_PROFILE_UPDATE = "내 프로필 수정 성공";
    public static final String MY_USER_ID_RETRIEVE = "내 인덱스 아이디 조회 성공";
    public static final String PROFILE_RETRIEVE = "사용자 프로필 조회 성공";
    public static final String DELETE_ACCOUNT = "계정 삭제 성공";
    public static final String EMAIL_DUPLICATE_VERIFICATION = "이메일 중복 확인 결과";
    public static final String FCM_TOKEN_UPDATE = "fcm 토큰 업데이트";
    public static final String JWT_GENERATOR_MESSAGE = "Jwt 토큰 생성 성공";
    public static final String REQUEST_SIGN_UP_MESSAGE = "회원가입을 진행해야 합니다";
    public static final String HOME_POST_SUCCESS = "집 게시글 등록 성공";
    public static final String ADDRESS_VALIDATION_SUCCESS = "주소 반환 성공";
    public static final String HOME_IMAGE_DELETE_SUCCESS = "집 이미지 삭제 성공";
    public static final String USER_POSTS_RETRIEVE_SUCCESS = "내 게시글 조회 성공";
    public static final String HOME_RETRIEVE_SUCCESS = "집 게시글 조회 성공";
    public static final String HOME_UPDATE_SUCCESS = "집 게시글 수정 성공";
    public static final String HOME_IMAGE_UPDATE_SUCCESS = "집 게시글 사진 수정 성공";
    public static final String HOME_SELL_SUCCESS = "집 판매 완료";
    public static final String ALL_HOMES_RETRIEVE_SUCCESS = "모든 집 정보 조회 성공";
    public static final String HOMES_PAGING_SUCCESS = "집 게시글 페이징 조회 성공";
    public static final String HOME_DELETE_SUCCESS = "delete!";
    public static final String CITY_HOMES_RETRIEVE_SUCCESS = "city 이름으로 조회 성공";
    public static final String FAVORITE_HOMES_RETRIEVE_SUCCESS = "찜 목록 집 조회 성공";
    public static final String CHARGE_SUCCESS = "충전 완료";
    public static final String CHARGE_FAILED = "충전 완료";
    public static final String APPLY_WITH_DRAW = "출금 신청 완료";
}
