name: Deploy to EC2

on:
  push:
    branches:
      - fl-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build JARs (without tests)
        run: |
          ./gradlew :fl-api:assemble -Dspring.profiles.active=test
          ./gradlew :fl-chatting:assemble -Dspring.profiles.active=test

      - name: Build Docker images
        run: |
          docker build -t minseok2000/cozy-api ./fl-api
          docker build -t minseok2000/cozy-chatting ./fl-chatting

      - name: Save Docker images to tar
        run: |
          docker save minseok2000/cozy-api -o cozy-api.tar
          docker save minseok2000/cozy-chatting -o cozy-chatting.tar

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: List deployment files
        run: ls -alh

      # 모든 배포 파일 한번에 전송
      - name: Upload files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: |
            .env
            cozy-api.tar
            cozy-chatting.tar
            ./docker-compose.yml
          target: /home/ubuntu/

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            sudo docker-compose down || true
            sudo docker stop $(sudo docker ps -q) || true
            sudo systemctl stop redis || true

            sudo docker load -i cozy-api.tar
            sudo docker load -i cozy-chatting.tar

            if grep -q FIREBASE_KEY_BASE64 .env; then
              export $(grep FIREBASE_KEY_BASE64 .env | xargs)
              echo "$FIREBASE_KEY_BASE64" | base64 -d > firebase-key.json
              sudo chmod 644 firebase-key.json
              echo "[✔] firebase-key.json 복호화 완료"
            else
              echo "[!] .env 파일에 FIREBASE_KEY_BASE64 없음"; exit 1
            fi

            sudo docker-compose up -d
